version: "3.9"

services:
  database:
    image: mariadb:10.10.5
    ports:
      - "3307:3306"
    volumes:
      - db-emr:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EMR

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database

volumes:
  db-emr: